version: '3'

services:
  granada-db:
    container_name: granada-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: tzkt
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tzkt_db
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 0.0.0.0:5433:5432

  granada-api:
    container_name: granada-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - granada-db
    environment:
      TZKT_API_KESTREL__ENDPOINTS__HTTP__URL: http://0.0.0.0:5000
      TZKT_API_ConnectionStrings__DefaultConnection: server=granada-db;port=5432;database=tzkt_db;username=tzkt;password=qwerty;
    expose:
      - 5000
    ports:
      - 0.0.0.0:5010:5000

  granada-sync:
    container_name: granada-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      TZKT_TezosNode__Endpoint: https://rpc.tzkt.io/granadanet/
      TZKT_ConnectionStrings__DefaultConnection: server=granada-db;port=5432;database=tzkt_db;username=tzkt;password=qwerty;
    depends_on:
      - granada-db

volumes:
  postgres:
      
