version: '3'

services:
  ghostnet-db:
    container_name: ghostnet-db
    restart: always
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    volumes:
      - ghostnet_postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432

  ghostnet-api:
    container_name: ghostnet-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - ghostnet-db
    environment:
      ConnectionStrings__DefaultConnection: host=ghostnet-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
    ports:
      - 0.0.0.0:5010:5000

  ghostnet-sync:
    container_name: ghostnet-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      ConnectionStrings__DefaultConnection: host=ghostnet-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5001
      TezosNode__Endpoint: https://rpc.tzkt.io/ghostnet/
      Protocols__Diagnostics: false
    depends_on:
      - ghostnet-db
    ports:
      - 0.0.0.0:5011:5001

volumes:
  ghostnet_postgres:
