version: '3'

services:
  ghost-db:
    container_name: ghost-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    volumes:
      - ghost_postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432

  ghost-api:
    container_name: ghost-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - ghost-db
    environment:
      ConnectionStrings__DefaultConnection: host=ghost-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
    ports:
      - 0.0.0.0:5010:5000

  ghost-sync:
    container_name: ghost-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      ConnectionStrings__DefaultConnection: host=ghost-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5001
      TezosNode__Endpoint: https://rpc.tzkt.io/ghostnet/
    depends_on:
      - ghost-db
    ports:
      - 0.0.0.0:5011:5001

volumes:
  ghost_postgres:
