version: '3'

services:
  paris-db:
    container_name: paris-db
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    volumes:
      - paris-postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5435:5432

  paris-api:
    container_name: paris-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - paris-db
    environment:
      ConnectionStrings__DefaultConnection: host=paris-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
    ports:
      - 0.0.0.0:5030:5000

  paris-sync:
    container_name: paris-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      ConnectionStrings__DefaultConnection: host=paris-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};command timeout=${COMMAND_TIMEOUT:-600};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5001
      TezosNode__Endpoint: https://rpc.tzkt.io/parisnet/
    depends_on:
      - paris-db
    ports:
      - 0.0.0.0:5031:5001

volumes:
  paris-postgres:
