FROM cirrusci/wget

RUN wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-NbqqaC1KSW2rKXS-YDh1iq301-VKjoS' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-NbqqaC1KSW2rKXS-YDh1iq301-VKjoS" -O tzkt_db.backup && rm -rf /tmp/cookies.txt
