// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tzkt.Data;
using Tzkt.Data.Models;

namespace Tzkt.Data.Migrations
{
    [DbContext(typeof(TzktContext))]
    partial class TzktContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Tzkt.Data.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("character(36)")
                        .IsFixedLength(true)
                        .HasMaxLength(36);

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("Contracts")
                        .HasColumnType("integer");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<int?>("DelegateId")
                        .HasColumnType("integer");

                    b.Property<int?>("DelegationLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DelegationsCount")
                        .HasColumnType("integer");

                    b.Property<int>("FirstLevel")
                        .HasColumnType("integer");

                    b.Property<int>("LastLevel")
                        .HasColumnType("integer");

                    b.Property<int>("OriginationsCount")
                        .HasColumnType("integer");

                    b.Property<int>("RevealsCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Staked")
                        .HasColumnType("boolean");

                    b.Property<int>("TransactionsCount")
                        .HasColumnType("integer");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("DelegateId");

                    b.HasIndex("FirstLevel");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasDiscriminator<byte>("Type");
                });

            modelBuilder.Entity("Tzkt.Data.Models.ActivationOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Level");

                    b.HasIndex("OpHash");

                    b.ToTable("ActivationOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.AppState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("GlobalCounter")
                        .HasColumnType("integer");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ManagerCounter")
                        .HasColumnType("integer");

                    b.Property<string>("NextProtocol")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<bool>("Synced")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("AppState");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            GlobalCounter = 0,
                            Hash = "",
                            Level = -1,
                            ManagerCounter = 0,
                            NextProtocol = "",
                            Protocol = "",
                            Synced = false,
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Tzkt.Data.Models.BallotOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Vote")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("OpHash");

                    b.HasIndex("PeriodId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("SenderId");

                    b.ToTable("BallotOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BakerId")
                        .HasColumnType("integer");

                    b.Property<int>("Events")
                        .HasColumnType("integer");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Operations")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("ProtoCode")
                        .HasColumnType("integer");

                    b.Property<int?>("ResetDeactivation")
                        .HasColumnType("integer");

                    b.Property<int?>("RevelationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Validations")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BakerId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Level")
                        .IsUnique();

                    b.HasIndex("ProtoCode");

                    b.HasIndex("RevelationId")
                        .IsUnique();

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Tzkt.Data.Models.DelegationOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("AllocationFee")
                        .HasColumnType("bigint");

                    b.Property<long>("BakerFee")
                        .HasColumnType("bigint");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<int?>("DelegateId")
                        .HasColumnType("integer");

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<int>("GasLimit")
                        .HasColumnType("integer");

                    b.Property<int>("GasUsed")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("Nonce")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResetDeactivation")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<long?>("StorageFee")
                        .HasColumnType("bigint");

                    b.Property<int>("StorageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("StorageUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DelegateId");

                    b.HasIndex("Level");

                    b.HasIndex("OpHash");

                    b.HasIndex("ParentId");

                    b.HasIndex("SenderId");

                    b.ToTable("DelegationOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.DoubleBakingOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccusedLevel")
                        .HasColumnType("integer");

                    b.Property<int>("AccuserId")
                        .HasColumnType("integer");

                    b.Property<long>("AccuserReward")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("OffenderId")
                        .HasColumnType("integer");

                    b.Property<long>("OffenderLostDeposit")
                        .HasColumnType("bigint");

                    b.Property<long>("OffenderLostFee")
                        .HasColumnType("bigint");

                    b.Property<long>("OffenderLostReward")
                        .HasColumnType("bigint");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccuserId");

                    b.HasIndex("Level");

                    b.HasIndex("OffenderId");

                    b.HasIndex("OpHash");

                    b.ToTable("DoubleBakingOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.DoubleEndorsingOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccusedLevel")
                        .HasColumnType("integer");

                    b.Property<int>("AccuserId")
                        .HasColumnType("integer");

                    b.Property<long>("AccuserReward")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("OffenderId")
                        .HasColumnType("integer");

                    b.Property<long>("OffenderLostDeposit")
                        .HasColumnType("bigint");

                    b.Property<long>("OffenderLostFee")
                        .HasColumnType("bigint");

                    b.Property<long>("OffenderLostReward")
                        .HasColumnType("bigint");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccuserId");

                    b.HasIndex("Level");

                    b.HasIndex("OffenderId");

                    b.HasIndex("OpHash");

                    b.ToTable("DoubleEndorsingOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.EndorsementOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DelegateId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int?>("ResetDeactivation")
                        .HasColumnType("integer");

                    b.Property<long>("Reward")
                        .HasColumnType("bigint");

                    b.Property<int>("Slots")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DelegateId");

                    b.HasIndex("Level");

                    b.HasIndex("OpHash");

                    b.ToTable("EndorsementOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.NonceRevelationOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int>("RevealedLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("OpHash");

                    b.HasIndex("SenderId");

                    b.ToTable("NonceRevelationOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.OriginationOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("AllocationFee")
                        .HasColumnType("bigint");

                    b.Property<long>("BakerFee")
                        .HasColumnType("bigint");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int?>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<int?>("DelegateId")
                        .HasColumnType("integer");

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<int>("GasLimit")
                        .HasColumnType("integer");

                    b.Property<int>("GasUsed")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<int?>("Nonce")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<long?>("StorageFee")
                        .HasColumnType("bigint");

                    b.Property<int>("StorageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("StorageUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("DelegateId");

                    b.HasIndex("Level");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OpHash");

                    b.HasIndex("ParentId");

                    b.HasIndex("SenderId");

                    b.ToTable("OriginationOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ExplorationPeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Hash")
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int>("InitiatorId")
                        .HasColumnType("integer");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<int?>("PromotionPeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalPeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TestingPeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExplorationPeriodId")
                        .IsUnique();

                    b.HasIndex("InitiatorId");

                    b.HasIndex("PromotionPeriodId")
                        .IsUnique();

                    b.HasIndex("ProposalPeriodId");

                    b.HasIndex("TestingPeriodId")
                        .IsUnique();

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("Tzkt.Data.Models.ProposalOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("OpHash");

                    b.HasIndex("PeriodId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("SenderId");

                    b.ToTable("ProposalOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.Protocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("BlockDeposit")
                        .HasColumnType("bigint");

                    b.Property<long>("BlockReward")
                        .HasColumnType("bigint");

                    b.Property<int>("BlocksPerCommitment")
                        .HasColumnType("integer");

                    b.Property<int>("BlocksPerCycle")
                        .HasColumnType("integer");

                    b.Property<int>("BlocksPerSnapshot")
                        .HasColumnType("integer");

                    b.Property<int>("BlocksPerVoting")
                        .HasColumnType("integer");

                    b.Property<int>("ByteCost")
                        .HasColumnType("integer");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<long>("EndorsementDeposit")
                        .HasColumnType("bigint");

                    b.Property<long>("EndorsementReward")
                        .HasColumnType("bigint");

                    b.Property<int>("EndorsersPerBlock")
                        .HasColumnType("integer");

                    b.Property<int>("FirstLevel")
                        .HasColumnType("integer");

                    b.Property<int>("HardBlockGasLimit")
                        .HasColumnType("integer");

                    b.Property<int>("HardOperationGasLimit")
                        .HasColumnType("integer");

                    b.Property<int>("HardOperationStorageLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int>("LastLevel")
                        .HasColumnType("integer");

                    b.Property<int>("OriginationSize")
                        .HasColumnType("integer");

                    b.Property<int>("PreserverCycles")
                        .HasColumnType("integer");

                    b.Property<long>("RevelationReward")
                        .HasColumnType("bigint");

                    b.Property<int>("TimeBetweenBlocks")
                        .HasColumnType("integer");

                    b.Property<long>("TokensPerRoll")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Protocols");
                });

            modelBuilder.Entity("Tzkt.Data.Models.RevealOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("AllocationFee")
                        .HasColumnType("bigint");

                    b.Property<long>("BakerFee")
                        .HasColumnType("bigint");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<int>("GasLimit")
                        .HasColumnType("integer");

                    b.Property<int>("GasUsed")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<long?>("StorageFee")
                        .HasColumnType("bigint");

                    b.Property<int>("StorageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("StorageUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("OpHash");

                    b.HasIndex("SenderId");

                    b.ToTable("RevealOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.TransactionOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("AllocationFee")
                        .HasColumnType("bigint");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("BakerFee")
                        .HasColumnType("bigint");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<int>("GasLimit")
                        .HasColumnType("integer");

                    b.Property<int>("GasUsed")
                        .HasColumnType("integer");

                    b.Property<byte?>("InternalOperations")
                        .HasColumnType("smallint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("Nonce")
                        .HasColumnType("integer");

                    b.Property<string>("OpHash")
                        .IsRequired()
                        .HasColumnType("character(51)")
                        .IsFixedLength(true)
                        .HasMaxLength(51);

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResetDeactivation")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<long?>("StorageFee")
                        .HasColumnType("bigint");

                    b.Property<int>("StorageLimit")
                        .HasColumnType("integer");

                    b.Property<int>("StorageUsed")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("OpHash");

                    b.HasIndex("ParentId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TargetId");

                    b.ToTable("TransactionOps");
                });

            modelBuilder.Entity("Tzkt.Data.Models.VotingEpoch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VotingEpoches");
                });

            modelBuilder.Entity("Tzkt.Data.Models.VotingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<int>("EndLevel")
                        .HasColumnType("integer");

                    b.Property<int>("EpochId")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("StartLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EpochId");

                    b.ToTable("VotingPeriods");

                    b.HasDiscriminator<int>("Kind");
                });

            modelBuilder.Entity("Tzkt.Data.Models.VotingSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DelegateId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("Rolls")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("PeriodId", "DelegateId");

                    b.ToTable("VotingSnapshots");
                });

            modelBuilder.Entity("Tzkt.Data.Models.Contract", b =>
                {
                    b.HasBaseType("Tzkt.Data.Models.Account");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<byte>("Kind")
                        .HasColumnType("smallint");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Spendable")
                        .HasColumnType("boolean");

                    b.Property<int?>("WeirdDelegateId")
                        .HasColumnType("integer");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("WeirdDelegateId");

                    b.HasDiscriminator().HasValue((byte)2);
                });

            modelBuilder.Entity("Tzkt.Data.Models.User", b =>
                {
                    b.HasBaseType("Tzkt.Data.Models.Account");

                    b.Property<bool?>("Activation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AirDrop")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicKey")
                        .HasColumnType("character varying(55)")
                        .HasMaxLength(55);

                    b.HasDiscriminator().HasValue((byte)0);
                });

            modelBuilder.Entity("Tzkt.Data.Models.ExplorationPeriod", b =>
                {
                    b.HasBaseType("Tzkt.Data.Models.VotingPeriod");

                    b.Property<int>("Abstainings")
                        .HasColumnType("integer");

                    b.Property<int>("Approvals")
                        .HasColumnType("integer");

                    b.Property<int>("Participation")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalId")
                        .HasColumnType("integer");

                    b.Property<int>("Quorum")
                        .HasColumnType("integer");

                    b.Property<int>("Refusals")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStake")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Tzkt.Data.Models.PromotionPeriod", b =>
                {
                    b.HasBaseType("Tzkt.Data.Models.VotingPeriod");

                    b.Property<int>("Abstainings")
                        .HasColumnName("PromotionPeriod_Abstainings")
                        .HasColumnType("integer");

                    b.Property<int>("Approvals")
                        .HasColumnName("PromotionPeriod_Approvals")
                        .HasColumnType("integer");

                    b.Property<int>("Participation")
                        .HasColumnName("PromotionPeriod_Participation")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalId")
                        .HasColumnName("PromotionPeriod_ProposalId")
                        .HasColumnType("integer");

                    b.Property<int>("Quorum")
                        .HasColumnName("PromotionPeriod_Quorum")
                        .HasColumnType("integer");

                    b.Property<int>("Refusals")
                        .HasColumnName("PromotionPeriod_Refusals")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStake")
                        .HasColumnName("PromotionPeriod_TotalStake")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Tzkt.Data.Models.ProposalPeriod", b =>
                {
                    b.HasBaseType("Tzkt.Data.Models.VotingPeriod");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Tzkt.Data.Models.TestingPeriod", b =>
                {
                    b.HasBaseType("Tzkt.Data.Models.VotingPeriod");

                    b.Property<int>("ProposalId")
                        .HasColumnName("TestingPeriod_ProposalId")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Tzkt.Data.Models.Delegate", b =>
                {
                    b.HasBaseType("Tzkt.Data.Models.User");

                    b.Property<int>("ActivationLevel")
                        .HasColumnType("integer");

                    b.Property<int>("BallotsCount")
                        .HasColumnType("integer");

                    b.Property<int>("DeactivationLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Delegators")
                        .HasColumnType("integer");

                    b.Property<int>("DoubleBakingCount")
                        .HasColumnType("integer");

                    b.Property<int>("DoubleEndorsingCount")
                        .HasColumnType("integer");

                    b.Property<int>("EndorsementsCount")
                        .HasColumnType("integer");

                    b.Property<long>("FrozenDeposits")
                        .HasColumnType("bigint");

                    b.Property<long>("FrozenFees")
                        .HasColumnType("bigint");

                    b.Property<long>("FrozenRewards")
                        .HasColumnType("bigint");

                    b.Property<int>("NonceRevelationsCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalsCount")
                        .HasColumnType("integer");

                    b.Property<long>("StakingBalance")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("Tzkt.Data.Models.Account", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Delegate", "Delegate")
                        .WithMany("DelegatedAccounts")
                        .HasForeignKey("DelegateId");

                    b.HasOne("Tzkt.Data.Models.Block", "FirstBlock")
                        .WithMany("CreatedAccounts")
                        .HasForeignKey("FirstLevel")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.ActivationOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.User", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Activations")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.BallotOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Ballots")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.VotingPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Proposal", "Proposal")
                        .WithMany()
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Delegate", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.Block", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Delegate", "Baker")
                        .WithMany()
                        .HasForeignKey("BakerId");

                    b.HasOne("Tzkt.Data.Models.Protocol", "Protocol")
                        .WithMany()
                        .HasForeignKey("ProtoCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.NonceRevelationOperation", "Revelation")
                        .WithOne("RevealedBlock")
                        .HasForeignKey("Tzkt.Data.Models.Block", "RevelationId")
                        .HasPrincipalKey("Tzkt.Data.Models.NonceRevelationOperation", "RevealedLevel");
                });

            modelBuilder.Entity("Tzkt.Data.Models.DelegationOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Delegate", "Delegate")
                        .WithMany()
                        .HasForeignKey("DelegateId");

                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Delegations")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.TransactionOperation", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Tzkt.Data.Models.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.DoubleBakingOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Delegate", "Accuser")
                        .WithMany()
                        .HasForeignKey("AccuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("DoubleBakings")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Delegate", "Offender")
                        .WithMany()
                        .HasForeignKey("OffenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.DoubleEndorsingOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Delegate", "Accuser")
                        .WithMany()
                        .HasForeignKey("AccuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("DoubleEndorsings")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Delegate", "Offender")
                        .WithMany()
                        .HasForeignKey("OffenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.EndorsementOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Delegate", "Delegate")
                        .WithMany()
                        .HasForeignKey("DelegateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Endorsements")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.NonceRevelationOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Revelations")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Delegate", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.OriginationOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.HasOne("Tzkt.Data.Models.Delegate", "Delegate")
                        .WithMany()
                        .HasForeignKey("DelegateId");

                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Originations")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("Tzkt.Data.Models.TransactionOperation", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Tzkt.Data.Models.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.Proposal", b =>
                {
                    b.HasOne("Tzkt.Data.Models.ExplorationPeriod", "ExplorationPeriod")
                        .WithOne("Proposal")
                        .HasForeignKey("Tzkt.Data.Models.Proposal", "ExplorationPeriodId");

                    b.HasOne("Tzkt.Data.Models.Delegate", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.PromotionPeriod", "PromotionPeriod")
                        .WithOne("Proposal")
                        .HasForeignKey("Tzkt.Data.Models.Proposal", "PromotionPeriodId");

                    b.HasOne("Tzkt.Data.Models.ProposalPeriod", "ProposalPeriod")
                        .WithMany()
                        .HasForeignKey("ProposalPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.TestingPeriod", "TestingPeriod")
                        .WithOne("Proposal")
                        .HasForeignKey("Tzkt.Data.Models.Proposal", "TestingPeriodId");
                });

            modelBuilder.Entity("Tzkt.Data.Models.ProposalOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Proposals")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.VotingPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Proposal", "Proposal")
                        .WithMany()
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Delegate", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.RevealOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Reveals")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.TransactionOperation", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Block", "Block")
                        .WithMany("Transactions")
                        .HasForeignKey("Level")
                        .HasPrincipalKey("Level")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.TransactionOperation", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Tzkt.Data.Models.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tzkt.Data.Models.Account", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId");
                });

            modelBuilder.Entity("Tzkt.Data.Models.VotingPeriod", b =>
                {
                    b.HasOne("Tzkt.Data.Models.VotingEpoch", "Epoch")
                        .WithMany()
                        .HasForeignKey("EpochId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.VotingSnapshot", b =>
                {
                    b.HasOne("Tzkt.Data.Models.VotingPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tzkt.Data.Models.Contract", b =>
                {
                    b.HasOne("Tzkt.Data.Models.Account", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("Tzkt.Data.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("Tzkt.Data.Models.User", "WeirdDelegate")
                        .WithMany()
                        .HasForeignKey("WeirdDelegateId");
                });
#pragma warning restore 612, 618
        }
    }
}
