name: Dockerhub

on:
  push:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push MvKT Sync image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Mvkt.Sync/Dockerfile
          push: true
          tags: mavrykdynamics/mvkt-sync:latest

      - name: Build and push MvKT API image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Mvkt.Api/Dockerfile
          push: true
          tags: mavrykdynamics/mvkt-api:latest
          
      - name: Docker Hub MvKT Sync Description Update
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mavrykdynamics/mvkt-sync
          
      - name: Docker Hub MvKT API Description Update
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mavrykdynamics/mvkt-api