name: Dockerhub

on:
  push:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push TzKT Sync image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Tzkt.Sync/Dockerfile
          push: true
          tags: bakingbad/tzkt-sync:latest
          
      - name: Build and push TzKT API image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Tzkt.Api/Dockerfile
          push: true
          tags: bakingbad/tzkt-api:latest
          
      - name: Docker Hub TzKT Sync Description Update
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: bakingbad/tzkt-sync
          
      - name: Docker Hub TzKT API Description Update
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: bakingbad/tzkt-api